FROM apache/airflow:2.6.1
USER root
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         libpq-dev build-essential \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
USER airflow
RUN pip install --no-cache-dir pandas==1.3.4
RUN pip install --no-cache-dir requests==2.28.1
RUN pip install --no-cache-dir psycopg2==2.9.5
RUN pip install --no-cache-dir yfinance==0.2.18